# Generated by Django 4.1 on 2025-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("future", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="futuresorders",
            name="fee",
            field=models.FloatField(default=0),
        ),
    ]
